cls_home:
    path: /
    defaults: { _controller: ClsSiteBundle:Home:index }

cls_estimate:
    path: /orcamento
    methods: [GET]
    defaults: { _controller: ClsSiteBundle:Estimate:index }

cls_estimate_create:
    path: /orcamento
    methods: [POST]
    defaults: { _controller: ClsSiteBundle:Estimate:create }

cls_institutional:
    path: /empresa
    methods: [GET]
    defaults: { _controller: ClsSiteBundle:Institutional:index }

cls_services:
    path: /servicos
    methods: [GET]
    defaults: { _controller: ClsSiteBundle:Services:index }

cls_contact:
    path: /fale-conosco
    methods: [GET]
    defaults: { _controller: ClsSiteBundle:Contact:index }

cls_contact_send:
    path: /fale-conosco
    methods: [POST]
    defaults: { _controller: ClsSiteBundle:Contact:send }

cls_equipment_list:
    path: /equipamentos
    defaults: { _controller: ClsSiteBundle:Equipment:list }

cls_gallery:
    path: /galeria
    methods: [GET]
    defaults: { _controller: ClsSiteBundle:ImageGallery:index }