parameters:
#    cls_site.example.class: Cls\SiteBundle\Example

services:
    cls.form.type.estimate:
        class: Cls\SiteBundle\Form\EstimateType
        tags:
            - { name: form.type, alias: cls_type_estimate }