parameters:
#    cls_site.example.class: Cls\SiteBundle\Example

services:
#    cls_site.example:
#        class: %cls_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
