parameters:
#    cls_site.example.class: Cls\SiteBundle\Example

services:
    cls.form.type.estimate:
        class: Cls\SiteBundle\Form\EstimateType
        tags:
            - { name: form.type, alias: cls_type_estimate }

    cls.form.type.contact:
        class: Cls\SiteBundle\Form\ContactType
        tags:
            - { name: form.type, alias: cls_type_contact }

    cls.contact.mailer:
        class: Cls\SiteBundle\Mail\ContactMail
        arguments: ['@mailer', '@templating', '%mailer_user%']

    cls.estimate.mailer:
        class: Cls\SiteBundle\Mail\EstimateNotification
        arguments: ['@mailer', '@templating', '%mailer_user%']

    cls.admin.equipment:
        class: Cls\SiteBundle\Admin\EquipmentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Equipamentos }
        arguments: [null, Cls\SiteBundle\Entity\Equipment, null]